### ISSUE TITLE
dbt Test task fails with an error

### ISSUE THREAD

**Issue by shrutimantri** [kestra-io/plugin-dbt#89]
### Expected Behavior

dbt Test task example should succeed.

### Actual Behaviour

dbt Test task fails with the following error:

```
2024-02-17 21:55:51.965[Date: 2024-02-17T16:25:51.961151Z] [Thread: MainThread] [Type: FinishedRunningStats] Finished running  in 0 hours 0 minutes and 1.07 seconds (1.07s). 
2024-02-17 21:55:51.967[Date: 2024-02-17T16:25:51.964568Z] [Thread: MainThread] [Type: MainEncounteredError] Encountered an error:
Runtime Error
  HTTP Error: Failed to download extension "parquet" at URL "http://extensions.duckdb.org/v0.9.2/linux_arm64_gcc4/parquet.duckdb_extension.gz"
  Extension "parquet" is an existing extension.
   
2024-02-17 21:55:53.474Command failed with code 2
2024-02-17 21:55:53.474io.kestra.plugin.scripts.exec.scripts.runners.ScriptException: Command failed with code 2
	at io.kestra.plugin.scripts.exec.scripts.runners.DockerScriptRunner.run(DockerScriptRunner.java:171)
	at io.kestra.plugin.scripts.exec.scripts.runners.CommandsWrapper.run(CommandsWrapper.java:159)
	at io.kestra.plugin.dbt.cli.AbstractDbt.run(AbstractDbt.java:180)
	at io.kestra.plugin.dbt.cli.AbstractDbt.run(AbstractDbt.java:34)
	at io.kestra.core.runners.Worker$WorkerThread.run(Worker.java:729)
```
Similar error has been found on the following dbt tasks as well:
dbt Seed, dbt Build, dbt Run, dbt DbtCLI and dbt Compile
(6 tasks in total including dbt Test)

### Steps To Reproduce

1. Use the flow example as stated on [this](https://kestra.io/plugins/plugin-dbt/tasks/cli/io.kestra.plugin.dbt.cli.Test) page.
2. The flow execution results in an error.

### Environment Information

- Kestra Version: 0.14.4
- Plugin version: 0.14.4
- Operating System (OS / Docker / Kubernetes): Docker
- Java Version (If not docker): N/A

### Example flow

```
namespace: io.kestra.tests
id: dbt-test
tasks:
  - id: working-directory
    type: io.kestra.core.tasks.flows.WorkingDirectory
    tasks:
    - id: cloneRepository
      type: io.kestra.plugin.git.Clone
      url: https://github.com/kestra-io/dbt-demo
      branch: main
    - id: dbt-test
      type: io.kestra.plugin.dbt.cli.Test
      runner: DOCKER
      dbtPath: /usr/local/bin/dbt
      docker:
        image: ghcr.io/kestra-io/dbt-duckdb
      profiles: |
        jaffle_shop:
          outputs:
            dev:
              type: duckdb
              path: ':memory:'
              extensions:
                - parquet
          target: dev
```

**Comment by anna-geller** [comment]
thanks for the issue

the extension is an issue with dbt-duckdb, will fix it, but there is another error https://github.com/kestra-io/plugin-dbt/issues/91
